# Generated by Django 5.2.6 on 2025-09-12 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Уникальный адрес электронной почты, используемый для входа.', max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона в международном формате (например, +79991234567).', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('city', models.CharField(blank=True, help_text='Город проживания пользователя.', max_length=100, null=True, verbose_name='Город')),
                ('avatar', models.ImageField(blank=True, help_text='Изображение профиля пользователя. Поддерживаются JPG, PNG.', null=True, upload_to='user_avatars/', verbose_name='Аватарка')),
                ('is_active', models.BooleanField(default=True, help_text='Определяет, может ли пользователь войти в систему.', verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, имеет ли пользователь доступ к административной панели.', verbose_name='Персонал')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания учетной записи.', verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['email'],
            },
        ),
    ]
