# Generated by Django 5.2.6 on 2025-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_stripe_payment_intent_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
