# Generated by Django 5.2.6 on 2025-09-24 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец, к которому относится этот курс. При удалении круса — курсы удаляются.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_course",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец, к которому относится этот урок. При удалении урока — уроки удаляются.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_lesson",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Курс, к которому относится этот урок. При удалении урока — уроки удаляются.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="education.course",
                verbose_name="Курс",
            ),
        ),
    ]
